### ISSUE TITLE
TF_Question_Accueil §Un référentiel commun : Serait-t-il possible d'ajouter des liens hypertextes ? 

### ISSUE THREAD

**Issue by danco2022** [ansforge/IG-NOS#11]
Liens : 
Modèle des Objets de Santé (MOS) 
TRE_R87-TypeCarte 
Document  "« Conventions de nommage et de structure des nomenclatures et des tables »."

**Comment by dcohenAns** [comment]
Il y a bien les liens vers la convention de nommage. Merci
