### ISSUE TITLE
Pbme telechargt CSV 

### ISSUE THREAD

**Issue by dcohenAns** [ansforge/IG-NOS#21]
le fichier téléchargé est un fichier XML au lieu d'un fichier CSV
<img width="597" alt="image" src="https://github.com/ansforge/IG-NOS/assets/143615260/6b1c4afb-d097-46b5-a50e-223417e25858">

**Comment by M-Priour** [comment]
Le fichier csv est identique à celui du site du mos : 
- https://mos.esante.gouv.fr/NOS/TRE_A00-ProducteurDocNonPS/TRE_A00-ProducteurDocNonPS.tabs
- https://ansforge.github.io/IG-NOS/ig/main/NOS/CodeSystem-TRE-A00-ProducteurDocNonPS.tabs

**Comment by dcohenAns** [comment]
Merci pour ton retour.
Désolée, si je me trompe, mais sur le site, esanté, pour la TRE_A00, 
j'ai :
<img width="981" alt="image" src="https://github.com/ansforge/IG-NOS/assets/143615260/0b465878-c4c6-4890-abe2-e180376656ba">

**Comment by M-Priour** [comment]
Le résultat est identique quand on télécharge le fichier

**Comment by dcohenAns** [comment]
A présent, le .tabs est bien un fichier .tabs Merci
