### ISSUE TITLE
Problème sur le JDV "ValueSet-JDV-J255-SurspecialiteTransversale-RPPS.html"

### ISSUE THREAD

**Issue by M-Priour** [ansforge/IG-NOS#28]
# Description du problème
L'uri du codeSytem n'est pas correct : 
-"https://mos.esante.gouv.fr/NOS/TRE_R359-SurspecialiteTransversale

Il faudrait retrouver : 
-https://mos.esante.gouv.fr/NOS/TRE_R359-SurspecialiteTransversale/FHIR/TRE-R359-SurspecialiteTransversale
![image](https://github.com/ansforge/IG-NOS/assets/101335975/5fb18434-0b73-4a5b-ab2a-44e3491e626c)

# Page•s concernée•s

https://interop.esante.gouv.fr/ig/nos/ValueSet-JDV-J255-SurspecialiteTransversale-RPPS.html
# Fichier•s concerné•s

# Solution proposée

**Comment by 3abdel3ali** [comment]
@M-Priour  Ce JDV n'est pas sur le FTS en prod ! dans les logs j'ai des erreurs et du coup, il n'a pas été injecté

**Comment by M-Priour** [comment]
@dcohenAns @KerJac35 
Sur la publication du jour, le problème n'est pas corrigé.
Il manque un R dans le l'URI de la TRE
![image](https://github.com/ansforge/IG-NOS/assets/101335975/c6bd9fd0-6156-4d4e-926f-b0a04bcbb001)

**Comment by 3abdel3ali** [comment]
Je conforme cette erreur, elle a été remontée par le job Talend également 

[JDV5_log_UrlInconnue_2.csv](https://github.com/ansforge/IG-NOS/files/14833709/JDV5_log_UrlInconnue_2.csv)

**Comment by dcohenAns** [comment]
OK Merci @Maël. On va corriger

**Comment by dcohenAns** [comment]
Merci  @M-Priour  ca marche :)
