### ISSUE TITLE
L'ensemble des TRE (.zip, pdf, fhir...) ne se télécharge pas

### ISSUE THREAD

**Issue by tayeb83** [ansforge/IG-NOS#7]
# Description du problème
Quand on clique sur l'onglet téléchargement devant les TREs par exemple et on choisit un format, on a une erreur 404 (file not found) devant chaque format.

# Page•s concernée•s
https://ansforge.github.io/IG-NOS/ig/allNos/telechargement-tre.html

# Fichier•s concerné•s

# Solution proposée

**Comment by M-Priour** [comment]
Merci Tayeb, c'est corrigé
